CREATE DATABASE IF NOT EXISTS POLIPROFES;
USE POLIPROFES;

CREATE TABLE IF NOT EXISTS CARRERAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CARRERA VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATERIAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    MATERIA VARCHAR(50) NOT NULL,
    CARRERA_ID INT NOT NULL, 
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERAS(ID)
);

CREATE TABLE IF NOT EXISTS PROFESORES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50) NOT NULL,
    VERIFICADO BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESOR_MATERIAS(
	PROFESOR_ID INT,
    MATERIA_ID INT, 
    PRIMARY KEY(PROFESOR_ID, MATERIA_ID),
    FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESORES(ID),
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(ID)
);

CREATE TABLE IF NOT EXISTS ALUMNOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL, 
    CORREO VARCHAR(50) NOT NULL,
    CONTRASENIA VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMENTARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ALUMNOS_ID INT,
    PROFESORES_ID INT,
    CALIFICACION INT NOT NULL,
    DIFICULTAD ENUM('Muy Facil', 'Facil', 'Intermedio', 'Dificil', 'Muy Dificil') NOT NULL,
    COMENTARIO VARCHAR(350) NOT NULL,
    RECOMIENDA BOOL NOT NULL,
    APROBO BOOL NOT NULL,
    FECHA DATETIME NOT NULL,
    FOREIGN KEY (ALUMNOS_ID) REFERENCES ALUMNOS(ID),
    FOREIGN KEY (PROFESORES_ID) REFERENCES PROFESORES(ID)
);